### ISSUE TITLE
TextField dividerNormalHeight = 0.0 is not working at first time.

### ISSUE THREAD

**Issue by chinamcafee** [CosmicMind/Samples#15]
When I set dividerNormalHeight = 0.0 and run the app. the divider is still there, but after click it, the divider disappeared. Is that a bug? @danieldahan

**Comment by daniel-jonathan** [comment]
I will investigate this today with the work I am doing on the TextField.

**Comment by daniel-jonathan** [comment]
Hey! I made an update to this issue, would you be able to test the `development` branch to ensure it is fixed? Thank you!

**Comment by chinamcafee** [comment]
Hi, Thanks for your reply. Unfortunately, the issue still exists at development branch.  dividerNormalHeight = 0.0 still not working at first time.  But when I set dividerNormalColor = UIColor.clear directly and run the app,  it looks working well. The divider disappeared at first time.

**Comment by chinamcafee** [comment]
I have cloned Material and Sample to the same folder from Git and checkout development branch, then I execute ./install_all_pods.sh, after that I opend CosmicMind.xcworkspace and run TextField. I met the ERROR "Cannot load underlying module for 'Material' " either.  Is there any step omitted？

**Comment by daniel-jonathan** [comment]
When you do the install, it is for each individual project, not the workspace. The workspace is for when you want to include the frameworks manually. So please open the project workspace in the project you are looking to look at.

**Comment by daniel-jonathan** [comment]
As for this issue `dividerNormalHeight` remember you need to pod install the development branch, not the master. The proposed solution has not yet been released. I verified it all works perfectly. So please try again, thank you!

**Comment by daniel-jonathan** [comment]
The `dividerNormalHeight` is now in master :) [Material 2.3.3](https://github.com/CosmicMind/Material/releases/tag/2.3.3)
